# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Set status bar refresh interval to 15 seconds
set -g status-interval 15

# Reload TMUX environment
bind-key r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# Unbind default prefix key (Ctrl-b)
unbind C-b

# Set prefix keys
set -g prefix C-j
set -g prefix2 C-f

# Enable mouse support (clickable windows, panes, resizable panes)
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Use Alt-arrow keys without prefix to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Use Ctrl-Option-arrow keys without prefix to resize panes
bind -n C-M-Left resize-pane -L 5
bind -n C-M-Right resize-pane -R 5
bind -n C-M-Up resize-pane -U 5
bind -n C-M-Down resize-pane -D 5

# Shift-Option arrow to switch windows
unbind -n S-Left
unbind -n S-Right
bind -n S-M-Left previous-window
bind -n S-M-Right next-window

# Reorder windows with CTRL-SHIFT-arrow
bind-key -n C-S-Left swap-window -t -1
bind-key -n C-S-Right swap-window -t +1

# Set easier window split keys
bind-key v split-window -h
bind-key h split-window -v

# Basic settings
set -g status-position top
set -g pane-border-lines heavy

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'

# Theming
set -g status-justify left
set -g status-style "bg=default,fg=colour35"
set -g status-left ""
set -g status-left-length 0
set -g window-status-format " #I:#W "
set -g window-status-style "bg=default,fg=colour35"
set -g window-status-current-format " #I:#W "
set -g window-status-current-style "bg=#e0def4,fg=#232136,bold"
set -g status-right-length 100
set -g status-right-style "bg=default"
set -g status-right "#[bg=default,fg=colour35]#(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD 2>/dev/null) "

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
